exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - config.rb
  - sass
include:
  - .well-known
lsi: false
highlighter: rouge
safe: true
url: 'http://zacstewart.com'
markdown: kramdown
destination: ./build
